name: snownavi_mobile
description: SnowNavi Pose Analyzer - Mobile Edition. A professional pose analysis app for skiing coaches and sports analysts.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Video & Media
  video_player: ^2.8.1
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  
  # Pose Detection & Computer Vision
  google_mlkit_pose_detection: ^0.5.0
  
  # Storage & Data
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  
  # Network & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Utilities
  intl: ^0.20.2
  path: ^1.8.3
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  
  # UI Enhancements
  flutter_staggered_animations: ^1.1.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  
  # Development
  logger: ^2.0.2+1

  # JSON serialization
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/locales/
    - assets/models/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
